// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fptoui_fptoui,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.087569,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=319,HLS_VERSION=2022_2}" *)

module fptoui (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        c,
        c_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
output  [2:0] c;
output   c_ap_vld;

reg c_ap_vld;

wire   [31:0] reg_fu_65_p1;
wire   [7:0] exp_fu_81_p4;
wire   [22:0] trunc_ln241_fu_95_p1;
wire   [30:0] trunc_ln232_fu_69_p1;
wire   [8:0] zext_ln237_fu_91_p1;
wire  signed [8:0] sh_amt_fu_117_p2;
wire  signed [8:0] sh_amt_1_fu_145_p2;
wire   [23:0] zext_ln258_cast_fu_103_p3;
wire   [31:0] zext_ln258_fu_161_p1;
wire  signed [31:0] sext_ln252_fu_123_p1;
wire   [31:0] lshr_ln258_fu_165_p2;
wire   [2:0] trunc_ln254_fu_99_p1;
wire   [31:0] zext_ln276_fu_175_p1;
wire  signed [31:0] sext_ln252_1_fu_151_p1;
wire   [31:0] shl_ln276_fu_179_p2;
wire   [0:0] icmp_ln249_fu_111_p2;
wire   [0:0] icmp_ln253_fu_127_p2;
wire   [0:0] or_ln253_fu_189_p2;
wire   [0:0] icmp_ln256_fu_139_p2;
wire   [0:0] xor_ln253_fu_195_p2;
wire   [0:0] and_ln256_fu_201_p2;
wire   [0:0] icmp_ln255_fu_133_p2;
wire   [0:0] and_ln256_1_fu_207_p2;
wire   [2:0] trunc_ln265_fu_171_p1;
wire   [0:0] or_ln255_fu_221_p2;
wire   [0:0] icmp_ln274_fu_155_p2;
wire   [0:0] xor_ln255_fu_227_p2;
wire   [0:0] and_ln274_fu_233_p2;
wire   [2:0] trunc_ln276_fu_185_p1;
wire   [2:0] select_ln256_fu_213_p3;
wire   [0:0] xor_ln249_fu_247_p2;
wire   [0:0] and_ln253_fu_253_p2;
wire   [2:0] select_ln274_fu_239_p3;
wire   [2:0] select_ln253_fu_259_p3;
wire   [0:0] p_Result_s_fu_73_p3;
wire   [2:0] sub_ln455_fu_267_p2;
wire    ap_ce_reg;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

assign and_ln253_fu_253_p2 = (xor_ln249_fu_247_p2 & icmp_ln253_fu_127_p2);

assign and_ln256_1_fu_207_p2 = (icmp_ln255_fu_133_p2 & and_ln256_fu_201_p2);

assign and_ln256_fu_201_p2 = (xor_ln253_fu_195_p2 & icmp_ln256_fu_139_p2);

assign and_ln274_fu_233_p2 = (xor_ln255_fu_227_p2 & icmp_ln274_fu_155_p2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign c = ((p_Result_s_fu_73_p3[0:0] == 1'b1) ? sub_ln455_fu_267_p2 : select_ln253_fu_259_p3);

assign exp_fu_81_p4 = {{reg_fu_65_p1[30:23]}};

assign icmp_ln249_fu_111_p2 = ((trunc_ln232_fu_69_p1 == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_127_p2 = ((exp_fu_81_p4 == 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln255_fu_133_p2 = (($signed(sh_amt_fu_117_p2) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_139_p2 = (($signed(sh_amt_fu_117_p2) < $signed(9'd25)) ? 1'b1 : 1'b0);

assign icmp_ln274_fu_155_p2 = (($signed(sh_amt_1_fu_145_p2) < $signed(9'd3)) ? 1'b1 : 1'b0);

assign lshr_ln258_fu_165_p2 = zext_ln258_fu_161_p1 >> sext_ln252_fu_123_p1;

assign or_ln253_fu_189_p2 = (icmp_ln253_fu_127_p2 | icmp_ln249_fu_111_p2);

assign or_ln255_fu_221_p2 = (or_ln253_fu_189_p2 | icmp_ln255_fu_133_p2);

assign p_Result_s_fu_73_p3 = reg_fu_65_p1[32'd31];

assign reg_fu_65_p1 = a;

assign select_ln253_fu_259_p3 = ((and_ln253_fu_253_p2[0:0] == 1'b1) ? trunc_ln254_fu_99_p1 : select_ln274_fu_239_p3);

assign select_ln256_fu_213_p3 = ((and_ln256_1_fu_207_p2[0:0] == 1'b1) ? trunc_ln265_fu_171_p1 : 3'd0);

assign select_ln274_fu_239_p3 = ((and_ln274_fu_233_p2[0:0] == 1'b1) ? trunc_ln276_fu_185_p1 : select_ln256_fu_213_p3);

assign sext_ln252_1_fu_151_p1 = sh_amt_1_fu_145_p2;

assign sext_ln252_fu_123_p1 = sh_amt_fu_117_p2;

assign sh_amt_1_fu_145_p2 = ($signed(9'd0) - $signed(sh_amt_fu_117_p2));

assign sh_amt_fu_117_p2 = (9'd150 - zext_ln237_fu_91_p1);

assign shl_ln276_fu_179_p2 = zext_ln276_fu_175_p1 << sext_ln252_1_fu_151_p1;

assign sub_ln455_fu_267_p2 = (3'd0 - select_ln253_fu_259_p3);

assign trunc_ln232_fu_69_p1 = reg_fu_65_p1[30:0];

assign trunc_ln241_fu_95_p1 = reg_fu_65_p1[22:0];

assign trunc_ln254_fu_99_p1 = reg_fu_65_p1[2:0];

assign trunc_ln265_fu_171_p1 = lshr_ln258_fu_165_p2[2:0];

assign trunc_ln276_fu_185_p1 = shl_ln276_fu_179_p2[2:0];

assign xor_ln249_fu_247_p2 = (icmp_ln249_fu_111_p2 ^ 1'd1);

assign xor_ln253_fu_195_p2 = (or_ln253_fu_189_p2 ^ 1'd1);

assign xor_ln255_fu_227_p2 = (or_ln255_fu_221_p2 ^ 1'd1);

assign zext_ln237_fu_91_p1 = exp_fu_81_p4;

assign zext_ln258_cast_fu_103_p3 = {{1'd1}, {trunc_ln241_fu_95_p1}};

assign zext_ln258_fu_161_p1 = zext_ln258_cast_fu_103_p3;

assign zext_ln276_fu_175_p1 = trunc_ln254_fu_99_p1;

endmodule //fptoui3
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="uitofp_uitofp,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.014000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=1075,HLS_VERSION=2022_2}" *)

module uitofp (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        c,
        c_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
output  [31:0] c;
output   c_ap_vld;

reg c_ap_vld;

reg   [31:0] p_Result_4_fu_89_p4;
reg   [31:0] l_fu_99_p3;
wire   [31:0] sub_ln1098_fu_107_p2;
wire   [31:0] lsb_index_fu_113_p2;
wire   [30:0] tmp_fu_119_p4;
wire   [4:0] trunc_ln1102_fu_135_p1;
wire   [4:0] sub_ln1102_fu_139_p2;
wire   [31:0] zext_ln1102_fu_145_p1;
wire   [31:0] lshr_ln1102_fu_149_p2;
wire   [31:0] p_Result_s_fu_155_p2;
wire   [0:0] icmp_ln1101_fu_129_p2;
wire   [0:0] icmp_ln1102_fu_161_p2;
wire   [0:0] tmp_2_fu_173_p3;
wire   [31:0] shl_ln1104_fu_187_p2;
wire   [31:0] and_ln1104_fu_193_p2;
wire   [0:0] p_Result_1_fu_199_p2;
wire   [0:0] xor_ln1104_fu_181_p2;
wire   [0:0] and_ln1104_1_fu_205_p2;
wire   [0:0] a_1_fu_167_p2;
wire   [0:0] or_ln1104_fu_211_p2;
wire   [31:0] add_ln1113_fu_235_p2;
wire   [63:0] zext_ln1112_fu_225_p1;
wire   [63:0] zext_ln1113_fu_241_p1;
wire   [31:0] sub_ln1114_fu_251_p2;
wire   [63:0] zext_ln1114_fu_257_p1;
wire   [0:0] icmp_ln1113_fu_229_p2;
wire   [63:0] lshr_ln1113_fu_245_p2;
wire   [63:0] shl_ln1114_fu_261_p2;
wire   [1:0] or_ln_fu_217_p3;
wire   [63:0] m_fu_267_p3;
wire   [63:0] zext_ln1116_fu_275_p1;
wire   [63:0] m_1_fu_279_p2;
wire   [62:0] m_4_fu_285_p4;
wire   [0:0] p_Result_2_fu_299_p3;
wire   [7:0] select_ln1119_fu_307_p3;
wire   [7:0] trunc_ln1119_fu_315_p1;
wire   [7:0] add_ln1124_fu_319_p2;
wire   [63:0] zext_ln1117_fu_295_p1;
wire   [8:0] tmp_1_fu_325_p3;
wire   [63:0] p_Result_5_fu_333_p5;
wire   [0:0] icmp_ln1090_fu_83_p2;
wire   [31:0] LD_fu_345_p1;
wire    ap_ce_reg;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

assign LD_fu_345_p1 = p_Result_5_fu_333_p5[31:0];

assign a_1_fu_167_p2 = (icmp_ln1102_fu_161_p2 & icmp_ln1101_fu_129_p2);

assign add_ln1113_fu_235_p2 = ($signed(sub_ln1098_fu_107_p2) + $signed(32'd4294967271));

assign add_ln1124_fu_319_p2 = (select_ln1119_fu_307_p3 + trunc_ln1119_fu_315_p1);

assign and_ln1104_1_fu_205_p2 = (xor_ln1104_fu_181_p2 & p_Result_1_fu_199_p2);

assign and_ln1104_fu_193_p2 = (shl_ln1104_fu_187_p2 & a);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign c = ((icmp_ln1090_fu_83_p2[0:0] == 1'b1) ? 32'd0 : LD_fu_345_p1);

assign icmp_ln1090_fu_83_p2 = ((a == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1101_fu_129_p2 = (($signed(tmp_fu_119_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1102_fu_161_p2 = ((p_Result_s_fu_155_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1113_fu_229_p2 = (($signed(lsb_index_fu_113_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);


always @ (p_Result_4_fu_89_p4) begin
    if (p_Result_4_fu_89_p4[0] == 1'b1) begin
        l_fu_99_p3 = 32'd0;
    end else if (p_Result_4_fu_89_p4[1] == 1'b1) begin
        l_fu_99_p3 = 32'd1;
    end else if (p_Result_4_fu_89_p4[2] == 1'b1) begin
        l_fu_99_p3 = 32'd2;
    end else if (p_Result_4_fu_89_p4[3] == 1'b1) begin
        l_fu_99_p3 = 32'd3;
    end else if (p_Result_4_fu_89_p4[4] == 1'b1) begin
        l_fu_99_p3 = 32'd4;
    end else if (p_Result_4_fu_89_p4[5] == 1'b1) begin
        l_fu_99_p3 = 32'd5;
    end else if (p_Result_4_fu_89_p4[6] == 1'b1) begin
        l_fu_99_p3 = 32'd6;
    end else if (p_Result_4_fu_89_p4[7] == 1'b1) begin
        l_fu_99_p3 = 32'd7;
    end else if (p_Result_4_fu_89_p4[8] == 1'b1) begin
        l_fu_99_p3 = 32'd8;
    end else if (p_Result_4_fu_89_p4[9] == 1'b1) begin
        l_fu_99_p3 = 32'd9;
    end else if (p_Result_4_fu_89_p4[10] == 1'b1) begin
        l_fu_99_p3 = 32'd10;
    end else if (p_Result_4_fu_89_p4[11] == 1'b1) begin
        l_fu_99_p3 = 32'd11;
    end else if (p_Result_4_fu_89_p4[12] == 1'b1) begin
        l_fu_99_p3 = 32'd12;
    end else if (p_Result_4_fu_89_p4[13] == 1'b1) begin
        l_fu_99_p3 = 32'd13;
    end else if (p_Result_4_fu_89_p4[14] == 1'b1) begin
        l_fu_99_p3 = 32'd14;
    end else if (p_Result_4_fu_89_p4[15] == 1'b1) begin
        l_fu_99_p3 = 32'd15;
    end else if (p_Result_4_fu_89_p4[16] == 1'b1) begin
        l_fu_99_p3 = 32'd16;
    end else if (p_Result_4_fu_89_p4[17] == 1'b1) begin
        l_fu_99_p3 = 32'd17;
    end else if (p_Result_4_fu_89_p4[18] == 1'b1) begin
        l_fu_99_p3 = 32'd18;
    end else if (p_Result_4_fu_89_p4[19] == 1'b1) begin
        l_fu_99_p3 = 32'd19;
    end else if (p_Result_4_fu_89_p4[20] == 1'b1) begin
        l_fu_99_p3 = 32'd20;
    end else if (p_Result_4_fu_89_p4[21] == 1'b1) begin
        l_fu_99_p3 = 32'd21;
    end else if (p_Result_4_fu_89_p4[22] == 1'b1) begin
        l_fu_99_p3 = 32'd22;
    end else if (p_Result_4_fu_89_p4[23] == 1'b1) begin
        l_fu_99_p3 = 32'd23;
    end else if (p_Result_4_fu_89_p4[24] == 1'b1) begin
        l_fu_99_p3 = 32'd24;
    end else if (p_Result_4_fu_89_p4[25] == 1'b1) begin
        l_fu_99_p3 = 32'd25;
    end else if (p_Result_4_fu_89_p4[26] == 1'b1) begin
        l_fu_99_p3 = 32'd26;
    end else if (p_Result_4_fu_89_p4[27] == 1'b1) begin
        l_fu_99_p3 = 32'd27;
    end else if (p_Result_4_fu_89_p4[28] == 1'b1) begin
        l_fu_99_p3 = 32'd28;
    end else if (p_Result_4_fu_89_p4[29] == 1'b1) begin
        l_fu_99_p3 = 32'd29;
    end else if (p_Result_4_fu_89_p4[30] == 1'b1) begin
        l_fu_99_p3 = 32'd30;
    end else if (p_Result_4_fu_89_p4[31] == 1'b1) begin
        l_fu_99_p3 = 32'd31;
    end else begin
        l_fu_99_p3 = 32'd32;
    end
end

assign lsb_index_fu_113_p2 = ($signed(sub_ln1098_fu_107_p2) + $signed(32'd4294967272));

assign lshr_ln1102_fu_149_p2 = 32'd4294967295 >> zext_ln1102_fu_145_p1;

assign lshr_ln1113_fu_245_p2 = zext_ln1112_fu_225_p1 >> zext_ln1113_fu_241_p1;

assign m_1_fu_279_p2 = (m_fu_267_p3 + zext_ln1116_fu_275_p1);

assign m_4_fu_285_p4 = {{m_1_fu_279_p2[63:1]}};

assign m_fu_267_p3 = ((icmp_ln1113_fu_229_p2[0:0] == 1'b1) ? lshr_ln1113_fu_245_p2 : shl_ln1114_fu_261_p2);

assign or_ln1104_fu_211_p2 = (and_ln1104_1_fu_205_p2 | a_1_fu_167_p2);

assign or_ln_fu_217_p3 = {{1'd0}, {or_ln1104_fu_211_p2}};

assign p_Result_1_fu_199_p2 = ((and_ln1104_fu_193_p2 != 32'd0) ? 1'b1 : 1'b0);

assign p_Result_2_fu_299_p3 = m_1_fu_279_p2[32'd25];

integer ap_tvar_int_0;

always @ (a) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_4_fu_89_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_4_fu_89_p4[ap_tvar_int_0] = a[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_5_fu_333_p5 = {{zext_ln1117_fu_295_p1[63:32]}, {tmp_1_fu_325_p3}, {zext_ln1117_fu_295_p1[22:0]}};

assign p_Result_s_fu_155_p2 = (lshr_ln1102_fu_149_p2 & a);

assign select_ln1119_fu_307_p3 = ((p_Result_2_fu_299_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign shl_ln1104_fu_187_p2 = 32'd1 << lsb_index_fu_113_p2;

assign shl_ln1114_fu_261_p2 = zext_ln1112_fu_225_p1 << zext_ln1114_fu_257_p1;

assign sub_ln1098_fu_107_p2 = (32'd32 - l_fu_99_p3);

assign sub_ln1102_fu_139_p2 = ($signed(5'd25) - $signed(trunc_ln1102_fu_135_p1));

assign sub_ln1114_fu_251_p2 = (32'd25 - sub_ln1098_fu_107_p2);

assign tmp_1_fu_325_p3 = {{1'd0}, {add_ln1124_fu_319_p2}};

assign tmp_2_fu_173_p3 = lsb_index_fu_113_p2[32'd31];

assign tmp_fu_119_p4 = {{lsb_index_fu_113_p2[31:1]}};

assign trunc_ln1102_fu_135_p1 = sub_ln1098_fu_107_p2[4:0];

assign trunc_ln1119_fu_315_p1 = sub_ln1098_fu_107_p2[7:0];

assign xor_ln1104_fu_181_p2 = (tmp_2_fu_173_p3 ^ 1'd1);

assign zext_ln1102_fu_145_p1 = sub_ln1102_fu_139_p2;

assign zext_ln1112_fu_225_p1 = a;

assign zext_ln1113_fu_241_p1 = add_ln1113_fu_235_p2;

assign zext_ln1114_fu_257_p1 = sub_ln1114_fu_251_p2;

assign zext_ln1116_fu_275_p1 = or_ln_fu_217_p3;

assign zext_ln1117_fu_295_p1 = m_4_fu_285_p4;

endmodule //uitofp
