// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fcmp_fcmp,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.992000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=62,HLS_VERSION=2022_2}" *)

module fcmp (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        c,
        c_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
input  [31:0] b;
output   c;
output   c_ap_vld;

reg c_ap_vld;

wire   [31:0] bitcast_ln7_fu_61_p1;
wire   [31:0] bitcast_ln7_1_fu_79_p1;
wire   [7:0] tmp_fu_65_p4;
wire   [22:0] trunc_ln7_fu_75_p1;
wire   [0:0] icmp_ln7_1_fu_103_p2;
wire   [0:0] icmp_ln7_fu_97_p2;
wire   [7:0] tmp_1_fu_83_p4;
wire   [22:0] trunc_ln7_1_fu_93_p1;
wire   [0:0] icmp_ln7_3_fu_121_p2;
wire   [0:0] icmp_ln7_2_fu_115_p2;
wire   [0:0] or_ln7_fu_109_p2;
wire   [0:0] or_ln7_1_fu_127_p2;
wire   [0:0] and_ln7_fu_133_p2;
wire   [0:0] tmp_2_fu_55_p2;
wire    ap_ce_reg;

fcmp_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U1(
    .din0(a),
    .din1(b),
    .opcode(5'd3),
    .dout(tmp_2_fu_55_p2)
);

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

assign and_ln7_fu_133_p2 = (or_ln7_fu_109_p2 & or_ln7_1_fu_127_p2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign bitcast_ln7_1_fu_79_p1 = b;

assign bitcast_ln7_fu_61_p1 = a;

assign c = (tmp_2_fu_55_p2 & and_ln7_fu_133_p2);

assign icmp_ln7_1_fu_103_p2 = ((trunc_ln7_fu_75_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_2_fu_115_p2 = ((tmp_1_fu_83_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln7_3_fu_121_p2 = ((trunc_ln7_1_fu_93_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_97_p2 = ((tmp_fu_65_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln7_1_fu_127_p2 = (icmp_ln7_3_fu_121_p2 | icmp_ln7_2_fu_115_p2);

assign or_ln7_fu_109_p2 = (icmp_ln7_fu_97_p2 | icmp_ln7_1_fu_103_p2);

assign tmp_1_fu_83_p4 = {{bitcast_ln7_1_fu_79_p1[30:23]}};

assign tmp_fu_65_p4 = {{bitcast_ln7_fu_61_p1[30:23]}};

assign trunc_ln7_1_fu_93_p1 = bitcast_ln7_1_fu_79_p1[22:0];

assign trunc_ln7_fu_75_p1 = bitcast_ln7_fu_61_p1[22:0];

endmodule //fcmp
