// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="uitofp_uitofp,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.808563,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=836,HLS_VERSION=2022_2}" *)

module uitofp (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        c,
        c_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] a;
output  [31:0] c;
output   c_ap_vld;

reg c_ap_vld;

reg   [4:0] p_Result_s_fu_101_p4;
wire   [5:0] p_Result_6_fu_111_p3;
wire  signed [31:0] sext_ln1198_fu_119_p1;
reg   [31:0] l_fu_123_p3;
wire   [31:0] sub_ln1098_fu_131_p2;
wire   [31:0] lsb_index_fu_141_p2;
wire   [30:0] tmp_fu_147_p4;
wire   [2:0] trunc_ln1102_fu_163_p1;
wire   [2:0] sub_ln1102_fu_167_p2;
wire   [4:0] zext_ln1102_fu_173_p1;
wire   [4:0] lshr_ln1102_fu_177_p2;
wire   [4:0] p_Result_2_fu_183_p2;
wire   [0:0] icmp_ln1101_fu_157_p2;
wire   [0:0] icmp_ln1102_fu_189_p2;
wire   [0:0] tmp_2_fu_201_p3;
wire   [4:0] trunc_ln1099_fu_137_p1;
wire   [4:0] add_ln1104_fu_215_p2;
wire   [4:0] shl_ln1104_fu_221_p2;
wire   [4:0] and_ln1104_fu_227_p2;
wire   [0:0] p_Result_3_fu_233_p2;
wire   [0:0] xor_ln1104_fu_209_p2;
wire   [0:0] and_ln1104_1_fu_239_p2;
wire   [0:0] a_1_fu_195_p2;
wire   [0:0] or_ln1104_fu_245_p2;
wire   [31:0] add_ln1113_fu_269_p2;
wire   [63:0] zext_ln1112_fu_259_p1;
wire   [63:0] zext_ln1113_fu_275_p1;
wire   [31:0] sub_ln1114_fu_285_p2;
wire   [63:0] zext_ln1114_fu_291_p1;
wire   [0:0] icmp_ln1113_fu_263_p2;
wire   [63:0] lshr_ln1113_fu_279_p2;
wire   [63:0] shl_ln1114_fu_295_p2;
wire   [1:0] or_ln_fu_251_p3;
wire   [63:0] m_fu_301_p3;
wire   [63:0] zext_ln1116_fu_309_p1;
wire   [63:0] m_1_fu_313_p2;
wire   [62:0] m_4_fu_319_p4;
wire   [0:0] p_Result_4_fu_333_p3;
wire   [7:0] select_ln1119_fu_341_p3;
wire   [7:0] trunc_ln1119_fu_349_p1;
wire   [7:0] add_ln1124_fu_353_p2;
wire   [63:0] zext_ln1117_fu_329_p1;
wire   [8:0] tmp_1_fu_359_p3;
wire   [63:0] p_Result_7_fu_367_p5;
wire   [0:0] icmp_ln1090_fu_95_p2;
wire   [31:0] LD_fu_379_p1;
wire    ap_ce_reg;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

assign LD_fu_379_p1 = p_Result_7_fu_367_p5[31:0];

assign a_1_fu_195_p2 = (icmp_ln1102_fu_189_p2 & icmp_ln1101_fu_157_p2);

assign add_ln1104_fu_215_p2 = (trunc_ln1099_fu_137_p1 + 5'd8);

assign add_ln1113_fu_269_p2 = ($signed(sub_ln1098_fu_131_p2) + $signed(32'd4294967271));

assign add_ln1124_fu_353_p2 = (select_ln1119_fu_341_p3 + trunc_ln1119_fu_349_p1);

assign and_ln1104_1_fu_239_p2 = (xor_ln1104_fu_209_p2 & p_Result_3_fu_233_p2);

assign and_ln1104_fu_227_p2 = (shl_ln1104_fu_221_p2 & a);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign c = ((icmp_ln1090_fu_95_p2[0:0] == 1'b1) ? 32'd0 : LD_fu_379_p1);

assign icmp_ln1090_fu_95_p2 = ((a == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1101_fu_157_p2 = (($signed(tmp_fu_147_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1102_fu_189_p2 = ((p_Result_2_fu_183_p2 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1113_fu_263_p2 = (($signed(lsb_index_fu_141_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);


always @ (sext_ln1198_fu_119_p1) begin
    if (sext_ln1198_fu_119_p1[0] == 1'b1) begin
        l_fu_123_p3 = 32'd0;
    end else if (sext_ln1198_fu_119_p1[1] == 1'b1) begin
        l_fu_123_p3 = 32'd1;
    end else if (sext_ln1198_fu_119_p1[2] == 1'b1) begin
        l_fu_123_p3 = 32'd2;
    end else if (sext_ln1198_fu_119_p1[3] == 1'b1) begin
        l_fu_123_p3 = 32'd3;
    end else if (sext_ln1198_fu_119_p1[4] == 1'b1) begin
        l_fu_123_p3 = 32'd4;
    end else if (sext_ln1198_fu_119_p1[5] == 1'b1) begin
        l_fu_123_p3 = 32'd5;
    end else if (sext_ln1198_fu_119_p1[6] == 1'b1) begin
        l_fu_123_p3 = 32'd6;
    end else if (sext_ln1198_fu_119_p1[7] == 1'b1) begin
        l_fu_123_p3 = 32'd7;
    end else if (sext_ln1198_fu_119_p1[8] == 1'b1) begin
        l_fu_123_p3 = 32'd8;
    end else if (sext_ln1198_fu_119_p1[9] == 1'b1) begin
        l_fu_123_p3 = 32'd9;
    end else if (sext_ln1198_fu_119_p1[10] == 1'b1) begin
        l_fu_123_p3 = 32'd10;
    end else if (sext_ln1198_fu_119_p1[11] == 1'b1) begin
        l_fu_123_p3 = 32'd11;
    end else if (sext_ln1198_fu_119_p1[12] == 1'b1) begin
        l_fu_123_p3 = 32'd12;
    end else if (sext_ln1198_fu_119_p1[13] == 1'b1) begin
        l_fu_123_p3 = 32'd13;
    end else if (sext_ln1198_fu_119_p1[14] == 1'b1) begin
        l_fu_123_p3 = 32'd14;
    end else if (sext_ln1198_fu_119_p1[15] == 1'b1) begin
        l_fu_123_p3 = 32'd15;
    end else if (sext_ln1198_fu_119_p1[16] == 1'b1) begin
        l_fu_123_p3 = 32'd16;
    end else if (sext_ln1198_fu_119_p1[17] == 1'b1) begin
        l_fu_123_p3 = 32'd17;
    end else if (sext_ln1198_fu_119_p1[18] == 1'b1) begin
        l_fu_123_p3 = 32'd18;
    end else if (sext_ln1198_fu_119_p1[19] == 1'b1) begin
        l_fu_123_p3 = 32'd19;
    end else if (sext_ln1198_fu_119_p1[20] == 1'b1) begin
        l_fu_123_p3 = 32'd20;
    end else if (sext_ln1198_fu_119_p1[21] == 1'b1) begin
        l_fu_123_p3 = 32'd21;
    end else if (sext_ln1198_fu_119_p1[22] == 1'b1) begin
        l_fu_123_p3 = 32'd22;
    end else if (sext_ln1198_fu_119_p1[23] == 1'b1) begin
        l_fu_123_p3 = 32'd23;
    end else if (sext_ln1198_fu_119_p1[24] == 1'b1) begin
        l_fu_123_p3 = 32'd24;
    end else if (sext_ln1198_fu_119_p1[25] == 1'b1) begin
        l_fu_123_p3 = 32'd25;
    end else if (sext_ln1198_fu_119_p1[26] == 1'b1) begin
        l_fu_123_p3 = 32'd26;
    end else if (sext_ln1198_fu_119_p1[27] == 1'b1) begin
        l_fu_123_p3 = 32'd27;
    end else if (sext_ln1198_fu_119_p1[28] == 1'b1) begin
        l_fu_123_p3 = 32'd28;
    end else if (sext_ln1198_fu_119_p1[29] == 1'b1) begin
        l_fu_123_p3 = 32'd29;
    end else if (sext_ln1198_fu_119_p1[30] == 1'b1) begin
        l_fu_123_p3 = 32'd30;
    end else if (sext_ln1198_fu_119_p1[31] == 1'b1) begin
        l_fu_123_p3 = 32'd31;
    end else begin
        l_fu_123_p3 = 32'd32;
    end
end

assign lsb_index_fu_141_p2 = ($signed(sub_ln1098_fu_131_p2) + $signed(32'd4294967272));

assign lshr_ln1102_fu_177_p2 = 5'd31 >> zext_ln1102_fu_173_p1;

assign lshr_ln1113_fu_279_p2 = zext_ln1112_fu_259_p1 >> zext_ln1113_fu_275_p1;

assign m_1_fu_313_p2 = (m_fu_301_p3 + zext_ln1116_fu_309_p1);

assign m_4_fu_319_p4 = {{m_1_fu_313_p2[63:1]}};

assign m_fu_301_p3 = ((icmp_ln1113_fu_263_p2[0:0] == 1'b1) ? lshr_ln1113_fu_279_p2 : shl_ln1114_fu_295_p2);

assign or_ln1104_fu_245_p2 = (and_ln1104_1_fu_239_p2 | a_1_fu_195_p2);

assign or_ln_fu_251_p3 = {{1'd0}, {or_ln1104_fu_245_p2}};

assign p_Result_2_fu_183_p2 = (lshr_ln1102_fu_177_p2 & a);

assign p_Result_3_fu_233_p2 = ((and_ln1104_fu_227_p2 != 5'd0) ? 1'b1 : 1'b0);

assign p_Result_4_fu_333_p3 = m_1_fu_313_p2[32'd25];

assign p_Result_6_fu_111_p3 = {{1'd1}, {p_Result_s_fu_101_p4}};

assign p_Result_7_fu_367_p5 = {{zext_ln1117_fu_329_p1[63:32]}, {tmp_1_fu_359_p3}, {zext_ln1117_fu_329_p1[22:0]}};

integer ap_tvar_int_0;

always @ (a) begin
    for (ap_tvar_int_0 = 5 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 4 - 0) begin
            p_Result_s_fu_101_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_101_p4[ap_tvar_int_0] = a[4 - ap_tvar_int_0];
        end
    end
end

assign select_ln1119_fu_341_p3 = ((p_Result_4_fu_333_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign sext_ln1198_fu_119_p1 = $signed(p_Result_6_fu_111_p3);

assign shl_ln1104_fu_221_p2 = 5'd1 << add_ln1104_fu_215_p2;

assign shl_ln1114_fu_295_p2 = zext_ln1112_fu_259_p1 << zext_ln1114_fu_291_p1;

assign sub_ln1098_fu_131_p2 = (32'd5 - l_fu_123_p3);

assign sub_ln1102_fu_167_p2 = ($signed(3'd6) - $signed(trunc_ln1102_fu_163_p1));

assign sub_ln1114_fu_285_p2 = (32'd25 - sub_ln1098_fu_131_p2);

assign tmp_1_fu_359_p3 = {{1'd0}, {add_ln1124_fu_353_p2}};

assign tmp_2_fu_201_p3 = lsb_index_fu_141_p2[32'd31];

assign tmp_fu_147_p4 = {{lsb_index_fu_141_p2[31:1]}};

assign trunc_ln1099_fu_137_p1 = sub_ln1098_fu_131_p2[4:0];

assign trunc_ln1102_fu_163_p1 = sub_ln1098_fu_131_p2[2:0];

assign trunc_ln1119_fu_349_p1 = sub_ln1098_fu_131_p2[7:0];

assign xor_ln1104_fu_209_p2 = (tmp_2_fu_201_p3 ^ 1'd1);

assign zext_ln1102_fu_173_p1 = sub_ln1102_fu_167_p2;

assign zext_ln1112_fu_259_p1 = a;

assign zext_ln1113_fu_275_p1 = add_ln1113_fu_269_p2;

assign zext_ln1114_fu_291_p1 = sub_ln1114_fu_285_p2;

assign zext_ln1116_fu_309_p1 = or_ln_fu_251_p3;

assign zext_ln1117_fu_329_p1 = m_4_fu_319_p4;

endmodule //uitofp
