// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fcmp_fcmp,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.255000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6,HLS_SYN_LUT=96,HLS_VERSION=2022_2}" *)

module fcmp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        c,
        c_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] a;
input  [63:0] b;
output   c;
output   c_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg c_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln7_fu_111_p2;
reg   [0:0] icmp_ln7_reg_180;
wire   [0:0] icmp_ln7_1_fu_117_p2;
reg   [0:0] icmp_ln7_1_reg_185;
wire   [0:0] icmp_ln7_2_fu_123_p2;
reg   [0:0] icmp_ln7_2_reg_190;
wire   [0:0] icmp_ln7_3_fu_129_p2;
reg   [0:0] icmp_ln7_3_reg_195;
wire    ap_CS_fsm_state2;
wire   [63:0] bitcast_ln7_fu_75_p1;
wire   [63:0] bitcast_ln7_1_fu_93_p1;
wire   [10:0] tmp_1_fu_79_p4;
wire   [51:0] trunc_ln7_fu_89_p1;
wire   [10:0] tmp_2_fu_97_p4;
wire   [51:0] trunc_ln7_1_fu_107_p1;
wire   [0:0] or_ln7_fu_135_p2;
wire   [0:0] or_ln7_1_fu_139_p2;
wire   [0:0] and_ln7_fu_143_p2;
wire   [0:0] grp_fu_69_p2;
wire   [0:0] and_ln7_1_fu_149_p2;
wire   [0:0] grp_fu_57_p2;
wire   [0:0] or_ln7_2_fu_155_p2;
wire   [0:0] grp_fu_63_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

fcmp_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a),
    .din1(64'd0),
    .ce(1'b1),
    .opcode(5'd8),
    .dout(grp_fu_57_p2)
);

fcmp_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b),
    .din1(64'd0),
    .ce(1'b1),
    .opcode(5'd8),
    .dout(grp_fu_63_p2)
);

fcmp_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a),
    .din1(b),
    .ce(1'b1),
    .opcode(5'd5),
    .dout(grp_fu_69_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln7_1_reg_185 <= icmp_ln7_1_fu_117_p2;
        icmp_ln7_2_reg_190 <= icmp_ln7_2_fu_123_p2;
        icmp_ln7_3_reg_195 <= icmp_ln7_3_fu_129_p2;
        icmp_ln7_reg_180 <= icmp_ln7_fu_111_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln7_1_fu_149_p2 = (grp_fu_69_p2 & and_ln7_fu_143_p2);

assign and_ln7_fu_143_p2 = (or_ln7_fu_135_p2 & or_ln7_1_fu_139_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign bitcast_ln7_1_fu_93_p1 = b;

assign bitcast_ln7_fu_75_p1 = a;

assign c = (or_ln7_2_fu_155_p2 | grp_fu_63_p2);

assign icmp_ln7_1_fu_117_p2 = ((trunc_ln7_fu_89_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_2_fu_123_p2 = ((tmp_2_fu_97_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln7_3_fu_129_p2 = ((trunc_ln7_1_fu_107_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_111_p2 = ((tmp_1_fu_79_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign or_ln7_1_fu_139_p2 = (icmp_ln7_3_reg_195 | icmp_ln7_2_reg_190);

assign or_ln7_2_fu_155_p2 = (grp_fu_57_p2 | and_ln7_1_fu_149_p2);

assign or_ln7_fu_135_p2 = (icmp_ln7_reg_180 | icmp_ln7_1_reg_185);

assign tmp_1_fu_79_p4 = {{bitcast_ln7_fu_75_p1[62:52]}};

assign tmp_2_fu_97_p4 = {{bitcast_ln7_1_fu_93_p1[62:52]}};

assign trunc_ln7_1_fu_107_p1 = bitcast_ln7_1_fu_93_p1[51:0];

assign trunc_ln7_fu_89_p1 = bitcast_ln7_fu_75_p1[51:0];

endmodule //fcmp
