// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fptosi_fptosi,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.951569,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=314,HLS_VERSION=2022_2}" *)

module fptosi (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        c,
        c_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
output  [1:0] c;
output   c_ap_vld;

reg c_ap_vld;

wire   [31:0] reg_fu_71_p1;
wire   [7:0] exp_fu_87_p4;
wire   [22:0] trunc_ln241_fu_101_p1;
wire   [30:0] trunc_ln232_fu_75_p1;
wire   [8:0] zext_ln237_fu_97_p1;
wire  signed [8:0] sh_amt_fu_123_p2;
wire  signed [8:0] sh_amt_1_fu_151_p2;
wire   [7:0] tmp_fu_161_p4;
wire   [23:0] zext_ln258_cast_fu_109_p3;
wire   [31:0] zext_ln258_fu_177_p1;
wire  signed [31:0] sext_ln252_fu_129_p1;
wire   [31:0] lshr_ln258_fu_181_p2;
wire  signed [1:0] trunc_ln254_fu_105_p1;
wire  signed [31:0] sext_ln276_fu_191_p1;
wire  signed [31:0] sext_ln252_1_fu_157_p1;
wire   [31:0] shl_ln276_fu_195_p2;
wire   [0:0] icmp_ln249_fu_117_p2;
wire   [0:0] icmp_ln253_fu_133_p2;
wire   [0:0] or_ln253_fu_205_p2;
wire   [0:0] icmp_ln256_fu_145_p2;
wire   [0:0] xor_ln253_fu_211_p2;
wire   [0:0] and_ln256_fu_217_p2;
wire   [0:0] icmp_ln255_fu_139_p2;
wire   [0:0] and_ln256_1_fu_223_p2;
wire   [1:0] trunc_ln265_fu_187_p1;
wire   [0:0] or_ln255_fu_237_p2;
wire   [0:0] icmp_ln274_fu_171_p2;
wire   [0:0] xor_ln255_fu_243_p2;
wire   [0:0] and_ln274_fu_249_p2;
wire   [1:0] trunc_ln276_fu_201_p1;
wire   [1:0] select_ln256_fu_229_p3;
wire   [0:0] xor_ln249_fu_263_p2;
wire   [0:0] and_ln253_fu_269_p2;
wire   [1:0] select_ln274_fu_255_p3;
wire   [1:0] select_ln253_fu_275_p3;
wire   [0:0] p_Result_s_fu_79_p3;
wire   [1:0] sub_ln455_fu_283_p2;
wire    ap_ce_reg;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

assign and_ln253_fu_269_p2 = (xor_ln249_fu_263_p2 & icmp_ln253_fu_133_p2);

assign and_ln256_1_fu_223_p2 = (icmp_ln255_fu_139_p2 & and_ln256_fu_217_p2);

assign and_ln256_fu_217_p2 = (xor_ln253_fu_211_p2 & icmp_ln256_fu_145_p2);

assign and_ln274_fu_249_p2 = (xor_ln255_fu_243_p2 & icmp_ln274_fu_171_p2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign c = ((p_Result_s_fu_79_p3[0:0] == 1'b1) ? sub_ln455_fu_283_p2 : select_ln253_fu_275_p3);

assign exp_fu_87_p4 = {{reg_fu_71_p1[30:23]}};

assign icmp_ln249_fu_117_p2 = ((trunc_ln232_fu_75_p1 == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_133_p2 = ((exp_fu_87_p4 == 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln255_fu_139_p2 = (($signed(sh_amt_fu_123_p2) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_145_p2 = (($signed(sh_amt_fu_123_p2) < $signed(9'd25)) ? 1'b1 : 1'b0);

assign icmp_ln274_fu_171_p2 = (($signed(tmp_fu_161_p4) < $signed(8'd1)) ? 1'b1 : 1'b0);

assign lshr_ln258_fu_181_p2 = zext_ln258_fu_177_p1 >> sext_ln252_fu_129_p1;

assign or_ln253_fu_205_p2 = (icmp_ln253_fu_133_p2 | icmp_ln249_fu_117_p2);

assign or_ln255_fu_237_p2 = (or_ln253_fu_205_p2 | icmp_ln255_fu_139_p2);

assign p_Result_s_fu_79_p3 = reg_fu_71_p1[32'd31];

assign reg_fu_71_p1 = a;

assign select_ln253_fu_275_p3 = ((and_ln253_fu_269_p2[0:0] == 1'b1) ? trunc_ln254_fu_105_p1 : select_ln274_fu_255_p3);

assign select_ln256_fu_229_p3 = ((and_ln256_1_fu_223_p2[0:0] == 1'b1) ? trunc_ln265_fu_187_p1 : 2'd0);

assign select_ln274_fu_255_p3 = ((and_ln274_fu_249_p2[0:0] == 1'b1) ? trunc_ln276_fu_201_p1 : select_ln256_fu_229_p3);

assign sext_ln252_1_fu_157_p1 = sh_amt_1_fu_151_p2;

assign sext_ln252_fu_129_p1 = sh_amt_fu_123_p2;

assign sext_ln276_fu_191_p1 = trunc_ln254_fu_105_p1;

assign sh_amt_1_fu_151_p2 = ($signed(9'd0) - $signed(sh_amt_fu_123_p2));

assign sh_amt_fu_123_p2 = (9'd150 - zext_ln237_fu_97_p1);

assign shl_ln276_fu_195_p2 = sext_ln276_fu_191_p1 << sext_ln252_1_fu_157_p1;

assign sub_ln455_fu_283_p2 = (2'd0 - select_ln253_fu_275_p3);

assign tmp_fu_161_p4 = {{sh_amt_1_fu_151_p2[8:1]}};

assign trunc_ln232_fu_75_p1 = reg_fu_71_p1[30:0];

assign trunc_ln241_fu_101_p1 = reg_fu_71_p1[22:0];

assign trunc_ln254_fu_105_p1 = reg_fu_71_p1[1:0];

assign trunc_ln265_fu_187_p1 = lshr_ln258_fu_181_p2[1:0];

assign trunc_ln276_fu_201_p1 = shl_ln276_fu_195_p2[1:0];

assign xor_ln249_fu_263_p2 = (icmp_ln249_fu_117_p2 ^ 1'd1);

assign xor_ln253_fu_211_p2 = (or_ln253_fu_205_p2 ^ 1'd1);

assign xor_ln255_fu_243_p2 = (or_ln255_fu_237_p2 ^ 1'd1);

assign zext_ln237_fu_97_p1 = exp_fu_87_p4;

assign zext_ln258_cast_fu_109_p3 = {{1'd1}, {trunc_ln241_fu_101_p1}};

assign zext_ln258_fu_177_p1 = zext_ln258_cast_fu_109_p3;

endmodule //fptosi
