// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mac_mac,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.494000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2022_2}" *)

module mac (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        c_i,
        c_o,
        c_o_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [14:0] a;
input  [14:0] b;
input  [14:0] c_i;
output  [14:0] c_o;
output   c_o_ap_vld;

reg c_o_ap_vld;

wire   [14:0] grp_fu_53_p3;
wire    ap_ce_reg;

mac_mac_muladd_15s_15s_15ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
mac_muladd_15s_15s_15ns_15_1_1_U1(
    .din0(b),
    .din1(a),
    .din2(c_i),
    .dout(grp_fu_53_p3)
);

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        c_o_ap_vld = 1'b1;
    end else begin
        c_o_ap_vld = 1'b0;
    end
end

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign c_o = grp_fu_53_p3;

endmodule //mac
