// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fptosi_fptosi,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.695771,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=386,HLS_VERSION=2022_2}" *)

module fptosi (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        c,
        c_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
output  [22:0] c;
output   c_ap_vld;

reg c_ap_vld;

wire   [31:0] reg_fu_65_p1;
wire   [7:0] exp_fu_81_p4;
wire   [22:0] trunc_ln241_fu_95_p1;
wire   [30:0] trunc_ln232_fu_69_p1;
wire   [8:0] zext_ln237_fu_91_p1;
wire  signed [8:0] sh_amt_fu_113_p2;
wire  signed [8:0] sh_amt_1_fu_141_p2;
wire   [23:0] zext_ln258_cast_fu_99_p3;
wire   [31:0] zext_ln258_fu_157_p1;
wire  signed [31:0] sext_ln252_fu_119_p1;
wire   [31:0] lshr_ln258_fu_161_p2;
wire  signed [31:0] sext_ln252_1_fu_147_p1;
wire   [22:0] sext_ln252_1cast_fu_171_p1;
wire   [0:0] icmp_ln249_fu_107_p2;
wire   [0:0] icmp_ln253_fu_123_p2;
wire   [0:0] or_ln253_fu_181_p2;
wire   [0:0] icmp_ln256_fu_135_p2;
wire   [0:0] xor_ln253_fu_187_p2;
wire   [0:0] and_ln256_fu_193_p2;
wire   [0:0] icmp_ln255_fu_129_p2;
wire   [0:0] and_ln256_1_fu_199_p2;
wire   [22:0] trunc_ln265_fu_167_p1;
wire   [0:0] or_ln255_fu_213_p2;
wire   [0:0] icmp_ln274_fu_151_p2;
wire   [0:0] xor_ln255_fu_219_p2;
wire   [0:0] and_ln274_fu_225_p2;
wire   [22:0] shl_ln276_fu_175_p2;
wire   [22:0] select_ln256_fu_205_p3;
wire   [0:0] xor_ln249_fu_239_p2;
wire   [0:0] and_ln253_fu_245_p2;
wire   [22:0] select_ln274_fu_231_p3;
wire   [22:0] select_ln253_fu_251_p3;
wire   [0:0] p_Result_s_fu_73_p3;
wire   [22:0] sub_ln455_fu_259_p2;
wire    ap_ce_reg;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

assign and_ln253_fu_245_p2 = (xor_ln249_fu_239_p2 & icmp_ln253_fu_123_p2);

assign and_ln256_1_fu_199_p2 = (icmp_ln255_fu_129_p2 & and_ln256_fu_193_p2);

assign and_ln256_fu_193_p2 = (xor_ln253_fu_187_p2 & icmp_ln256_fu_135_p2);

assign and_ln274_fu_225_p2 = (xor_ln255_fu_219_p2 & icmp_ln274_fu_151_p2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign c = ((p_Result_s_fu_73_p3[0:0] == 1'b1) ? sub_ln455_fu_259_p2 : select_ln253_fu_251_p3);

assign exp_fu_81_p4 = {{reg_fu_65_p1[30:23]}};

assign icmp_ln249_fu_107_p2 = ((trunc_ln232_fu_69_p1 == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_123_p2 = ((exp_fu_81_p4 == 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln255_fu_129_p2 = (($signed(sh_amt_fu_113_p2) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_135_p2 = (($signed(sh_amt_fu_113_p2) < $signed(9'd25)) ? 1'b1 : 1'b0);

assign icmp_ln274_fu_151_p2 = (($signed(sh_amt_1_fu_141_p2) < $signed(9'd23)) ? 1'b1 : 1'b0);

assign lshr_ln258_fu_161_p2 = zext_ln258_fu_157_p1 >> sext_ln252_fu_119_p1;

assign or_ln253_fu_181_p2 = (icmp_ln253_fu_123_p2 | icmp_ln249_fu_107_p2);

assign or_ln255_fu_213_p2 = (or_ln253_fu_181_p2 | icmp_ln255_fu_129_p2);

assign p_Result_s_fu_73_p3 = reg_fu_65_p1[32'd31];

assign reg_fu_65_p1 = a;

assign select_ln253_fu_251_p3 = ((and_ln253_fu_245_p2[0:0] == 1'b1) ? trunc_ln241_fu_95_p1 : select_ln274_fu_231_p3);

assign select_ln256_fu_205_p3 = ((and_ln256_1_fu_199_p2[0:0] == 1'b1) ? trunc_ln265_fu_167_p1 : 23'd0);

assign select_ln274_fu_231_p3 = ((and_ln274_fu_225_p2[0:0] == 1'b1) ? shl_ln276_fu_175_p2 : select_ln256_fu_205_p3);

assign sext_ln252_1_fu_147_p1 = sh_amt_1_fu_141_p2;

assign sext_ln252_1cast_fu_171_p1 = sext_ln252_1_fu_147_p1[22:0];

assign sext_ln252_fu_119_p1 = sh_amt_fu_113_p2;

assign sh_amt_1_fu_141_p2 = ($signed(9'd0) - $signed(sh_amt_fu_113_p2));

assign sh_amt_fu_113_p2 = (9'd150 - zext_ln237_fu_91_p1);

assign shl_ln276_fu_175_p2 = trunc_ln241_fu_95_p1 << sext_ln252_1cast_fu_171_p1;

assign sub_ln455_fu_259_p2 = (23'd0 - select_ln253_fu_251_p3);

assign trunc_ln232_fu_69_p1 = reg_fu_65_p1[30:0];

assign trunc_ln241_fu_95_p1 = reg_fu_65_p1[22:0];

assign trunc_ln265_fu_167_p1 = lshr_ln258_fu_161_p2[22:0];

assign xor_ln249_fu_239_p2 = (icmp_ln249_fu_107_p2 ^ 1'd1);

assign xor_ln253_fu_187_p2 = (or_ln253_fu_181_p2 ^ 1'd1);

assign xor_ln255_fu_219_p2 = (or_ln255_fu_213_p2 ^ 1'd1);

assign zext_ln237_fu_91_p1 = exp_fu_81_p4;

assign zext_ln258_cast_fu_99_p3 = {{1'd1}, {trunc_ln241_fu_95_p1}};

assign zext_ln258_fu_157_p1 = zext_ln258_cast_fu_99_p3;

endmodule //fptosi
